---
inherit_from:
  - https://raw.githubusercontent.com/meew0/discordrb/master/.rubocop.yml

Metrics/LineLength:
  Max: 119

Style/GlobalVars:
  AllowedVariables:
    - $config
    - $flavours
    - $poems
    - $lastfm
    - $bsuki
